// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/1/2026, 12:44:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/user1/agueda-proyect/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/frontend/plugins/**/*.{js,ts,mjs}","/home/user1/agueda-proyect/frontend/composables/**/*.{js,ts,mjs}","/home/user1/agueda-proyect/frontend/utils/**/*.{js,ts,mjs}","/home/user1/agueda-proyect/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;