// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/29/2026, 7:55:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/user1/agueda-proyect/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/plugins/**/*.{js,ts,mjs}","/home/user1/agueda-proyect/composables/**/*.{js,ts,mjs}","/home/user1/agueda-proyect/utils/**/*.{js,ts,mjs}","/home/user1/agueda-proyect/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user1/agueda-proyect/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;